### ISSUE TITLE
CTFW_INC_DIR being overridden

### ISSUE THREAD

**Issue by garand** [faithmade/churchthemes#1]
It seems that `CTFW_INC_DIR` is being overridden to the path for the plugin. I'm trying to use this plugin in conjunction with the other Church Theme Framework features and because the directory variable is being overridden, it is not including the rest of the framework properly.

**Comment by ataylorme** [comment]
@garand I changed the constants used in the plugin to use `CTFW_WIDGETS_` as a prefix instead of just `CTFW_`.

See [the commit](https://github.com/ChurchThemes-for-WordPress/ctfw-widgets/commit/ff72ba8e187e05eda36f879810970206c7acda69) for details
