### ISSUE TITLE
PHP Fatal Error - not allowing me to Update or Publish

### ISSUE THREAD

**Issue by angela-crist** [faithmade/churchthemes#17]
`[11-May-2015 21:01:33 UTC] PHP Fatal error:  Call to undefined function ctc_convert_to_datetime() in /dom10592/wp-content/plugins/churchthemes/includes/event-fields.php on line 45`

Need complete to complete QA

**Comment by angela-crist** [comment]
Looks like it is only effecting Events

**Comment by garand** [comment]
This is updated. I believe this plugin is setup to auto deploy, if not, let me know and I can deploy it manually.

**Comment by angela-crist** [comment]
Must not be set up for auto deploy:

http://lift.d.pr/1aVy5/3BGjdsga

Let me know when it is and I will test again.

**Comment by garand** [comment]
It's up there now.

**Comment by angela-crist** [comment]
I'm still getting the Pagely page for both save as draft and publish
http://lift.d.pr/1iKEr/2yIzVPts

**Comment by garand** [comment]
Take 2. Try again.

I updated it on Faithmade, not on the ChurchThemes site. It should be all set now.

**Comment by angela-crist** [comment]
Yippee it works :) Thank you!
