### ISSUE TITLE
Fatal Error on activation

### ISSUE THREAD

**Issue by mrpritchett** [faithmade/churchthemes#2]
Blank install from VVV with Rock Framework installed and activated.  No plugins except this one.

Fatal error: Call to undefined function is_plugin_active() in /srv/www/rock/htdocs/wp-content/plugins/churchthemes-plugin-master/ctfw-widgets.php on line 261

**Comment by chriswallace** [comment]
Should be resolved with the next update to the plugin, which will include a major rewrite.

**Comment by chriswallace** [comment]
Was this resolved?

**Comment by mrpritchett** [comment]
Will check ASAP.  Sorry, been off of GH for a while.
